title: Settings
data:
  site_name: 'Ruben van Erk'
  social:
    -
      id: 3WeKMnBk
      name: Twitter
      url: 'https://twitter.com/wrubenvanerk'
      icon: site/social-icons/twitter.svg
    -
      id: VdW1vSux
      name: Github
      url: 'https://github.com/rubenvanerk/'
      icon: site/social-icons/github.svg
    -
      id: CCDaaZwj
      name: Email
      url: 'mailto:hello@rubenvanerk.nl'
      icon: site/social-icons/email.svg
